version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: wallet-postgres
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: wallet-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/walletdb
      SPRING_DATASOURCE_USERNAME: wallet
      SPRING_DATASOURCE_PASSWORD: wallet
    depends_on:
      - postgres
